const start = document.getElementById('start'),
income = document.querySelector('.income'),
incomeAdd = income.querySelector('button'),
expenses = document.querySelector('.expenses'),
expensesAdd = expenses.querySelector('button'),
depositCheck = document.querySelector('#deposit-check'),
value = document.querySelectorAll('[class*="-value"]'),
salaryAmount = document.querySelector('.salary-amount'),
incomeTitle = document.querySelector('.income-title'),
incomeAmount = document.querySelector('.income-amount'),
additionalIncomeItem = document.querySelectorAll('.additional_income-item'),
expensesTitle = document.querySelector('.expenses-title'),
expensesAmount = document.querySelector('.expenses-amount'),
additionalExpensesItem = document.querySelector('.additional_expenses-item'),
periodSelect = document.querySelector('.period-select');
